# Populating DWH

## Import libraries

In [575]:
import sqlite3
import pandas as pd

## Define connections

In [576]:
SDM = sqlite3.connect('../SDM/BikeToDriveSDM.db')
DWH = sqlite3.connect('BikeToDriveDWH.db')

## Dim_Klant

In [577]:
df_klant_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_klant', SDM)
df_klant_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_klant', SDM)

df_klant_av = df_klant_av.drop('klantnr', axis=1)
df_klant_fv = df_klant_fv.drop('klantnr', axis=1)

df_klant_combined = pd.concat([df_klant_av, df_klant_fv]).drop_duplicates().reset_index(drop=True)

df_klant_combined.insert(0, 'klantnr', range(1, len(df_klant_combined) + 1))

df_klant_combined.to_sql('Dim_Klant', DWH, if_exists='replace', index=False)

df_klant_combined

,klantnr,naam,adres,woonplaats,geslacht,geboortedatum
0,1,Jan Jansen,Kerkstraat 12,Amsterdam,M,1985-03-22
1,2,Sophie de Boer,Lindelaan 8,Rotterdam,V,1990-07-11
2,3,Pieter Visser,Havenstraat 3,Den Haag,M,1978-11-05
3,4,Emma Smit,Boomgaard 22,Haarlem,V,1995-02-18
4,5,Tom Bakker,Stationsweg 44,Leiden,M,1982-09-09
5,6,Lisa Meijer,Dijkstraat 10,Zaandam,V,1993-12-30
6,7,Bart de Vries,Brouwersgracht 7,Delft,M,1976-06-06
7,8,Julia van Dijk,Plataanlaan 5,Hoorn,V,2000-01-15
8,9,Kevin Mol,Singel 99,Alkmaar,M,1989-08-01
9,10,Nina Groen,Waterstraat 16,Schiedam,V,1991-05-25
10,11,Daan Willems,Parklaan 31,Haarlem,M,1987-10-12
11,12,Eva Vos,Zomerweg 2,Zoetermeer,V,1996-04-03
12,13,Rik de Jong,Noorderstraat 88,Hilversum,M,1980-12-21
13,14,Mila Kuipers,Heemraadssingel 15,Rotterdam,V,1998-09-17
14,15,Sam Reinders,Beethovenlaan 13,Haarlem,M,1983-01-29
15,16,Fleur Schouten,Tulpenstraat 5,Amsterdam,V,1994-06-08
16,17,Lars van den Berg,Kade 101,Leiden,M,1988-03-02
17,18,Tess van Leeuwen,Markt 22,Dordrecht,V,1997-07-19
18,19,Jesse van Dam,Zuidlaan 7,Alphen aan den Rijn,M,1981-11-27
19,20,Noa Blom,Vondelstraat 18,Zaandam,V,2002-02-10
20,21,Robin Dekker,Rozenstraat 4,Delft,M,1992-11-23
21,22,Lieke de Wit,Tulpenpad 19,Den Haag,V,1986-07-12
22,23,Jeroen Hermans,Klaprooslaan 6,Zaandam,M,1999-05-04
23,24,Tessa van Vliet,Nieuwstraat 12,Leiden,V,2001-03-18
24,25,Bas Hendriks,IJsselstraat 2,Rotterdam,M,1984-10-30
25,26,Luna Hoekstra,Hortensialaan 1,Amstelveen,V,1997-08-07
26,27,Noah de Groot,Burgemeesterlaan 9,Haarlem,M,1990-12-02
27,28,Amber Peeters,Merellaan 18,Hoofddorp,V,1995-06-21
28,29,Mats Jonker,Kasteelstraat 7,Schiedam,M,1988-01-05
29,30,Isis Mulder,Goudenregenstraat 11,Dordrecht,V,2000-09-28

## Dim_Filiaal

In [578]:
df_filiaal_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_filiaal', SDM)
df_filiaal_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_filiaal', SDM)
df_filiaal_o = pd.read_sql_query('SELECT * FROM onderhoud_filiaal', SDM)

df_filiaal_av = df_filiaal_av.drop('filiaalnr', axis=1)
df_filiaal_fv = df_filiaal_fv.drop('filiaalnr', axis=1)
df_filiaal_o = df_filiaal_o.drop('filiaalnr', axis=1)

df_filiaal_combined = pd.concat([df_filiaal_av, df_filiaal_fv, df_filiaal_o]).drop_duplicates().reset_index(drop=True)

df_filiaal_combined.insert(0, 'filiaalnr', range(1, len(df_filiaal_combined) + 1))

df_filiaal_combined.to_sql('Dim_Filiaal', DWH, if_exists='replace', index=False)

df_filiaal_combined

   filiaalnr                    naam              adres      provincie
0          1     BikeWorld Amsterdam  Prinsengracht 100  Noord-Holland
1          2     FietsGigant Haarlem     Grote Markt 22  Noord-Holland
2          3  FietsExpress Rotterdam      Coolsingel 55   Zuid-Holland
3          4        CycleCity Leiden      Breestraat 48   Zuid-Holland
4          5       ZaanFiets Zaandam        Damstraat 5  Noord-Holland

## Dim_Monteur

In [579]:
df_monteur_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_monteur', SDM)
df_monteur_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_monteur', SDM)
df_monteur_o = pd.read_sql_query('SELECT * FROM onderhoud_monteur', SDM)

df_monteur_av = df_monteur_av.drop('monteurnr', axis=1)
df_monteur_fv = df_monteur_fv.drop('monteurNr', axis=1)
df_monteur_o = df_monteur_o.drop('monteurNr', axis=1)

df_monteur_combined = pd.concat([df_monteur_av, df_monteur_fv, df_monteur_o]).drop_duplicates().reset_index(drop=True)

df_monteur_combined.insert(0, 'monteurnr', range(1, len(df_monteur_combined) + 1))

df_monteur_combined.to_sql('Dim_Monteur', DWH, if_exists='replace', index=False)
df_monteur_combined

    monteurnr             naam  woonplaats  uurloon  filiaal
0           1     Tom van Dijk   Amsterdam    19.50        1
1           2   Lisa Verhoeven  Amstelveen    18.75        1
2           3    Kevin Jaspers     Zaandam    20.00        1
3           4     Romy Willems     Haarlem    17.80        2
4           5    Daan de Groot   Rotterdam    21.00        3
5           6  Sophie de Leeuw    Schiedam    19.90        3
6           7   Mark van Vliet   Dordrecht    20.25        3
7           8     Jesse Peters      Leiden    16.95        4
8           9       Eva Meijer  Zoetermeer    18.40        4
9          10   Milan de Bruin     Zaandam    17.25        2
10         11   Milan de Bruin     Zaandam    17.25        5
11         12   Sara de Koning     Haarlem    19.20        1
12         13       Nick Smits   Rotterdam    20.50        1
13         14     Laura Smeets   Amsterdam    18.80        1
14         15     Pim Scholten      Leiden    17.90        5
15         16    Tijn Hendriks     Zaandam    17.10        5

## Dim_Partner

In [580]:
df_leverancier_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_leverancier', SDM)
df_leverancier_ai = pd.read_sql_query('SELECT * FROM accessoire_inkoop_leverancier', SDM)

df_fabrikant_o    = pd.read_sql_query('SELECT * FROM onderhoud_fabrikant', SDM)
df_fabrikant_fv   = pd.read_sql_query('SELECT * FROM fiets_verkoop_fabrikant', SDM)
df_fabrikant_fi   = pd.read_sql_query('SELECT * FROM fiets_inkoop_fabrikant', SDM)

df_leverancier_av = df_leverancier_av.drop('leveranciernr', axis=1)
df_leverancier_ai = df_leverancier_ai.drop('leveranciernr', axis=1)
df_fabrikant_o    = df_fabrikant_o.drop('fabrikantnr', axis=1)
df_fabrikant_fv   = df_fabrikant_fv.drop('fabrikantnr', axis=1)
df_fabrikant_fi   = df_fabrikant_fi.drop('fabrikantnr', axis=1)

df_leverancier_combined = pd.concat([df_leverancier_av, df_leverancier_ai]).drop_duplicates().reset_index(drop=True)
df_fabrikant_combined   = pd.concat([df_fabrikant_o, df_fabrikant_fv, df_fabrikant_fi]).drop_duplicates().reset_index(drop=True)

df_leverancier_combined['type_partner'] = 'leverancier'
df_leverancier_combined.rename(columns={'woonplaats': 'plaats'}, inplace=True)
df_fabrikant_combined['type_partner'] = 'fabrikant'

df_partner_combined = pd.concat([df_leverancier_combined, df_fabrikant_combined]).drop_duplicates().reset_index(drop=True)
df_partner_combined.insert(0, 'partnernr', range(1, len(df_partner_combined) + 1))

df_partner_combined.to_sql('Dim_Partner', DWH, if_exists='replace', index=False)
df_partner_combined

,partnernr,naam,adres,plaats,type_partner
0,1,BikeParts BV,Fietsenstraat 12,Amsterdam,leverancier
1,2,CycleSupplies,Rembrandtlaan 7,Rotterdam,leverancier
2,3,TwoWheels Trading,Marktplein 5,Den Haag,leverancier
3,4,DutchBike Import,Kade 22,Leiden,leverancier
4,5,UrbanGear NL,Stationsweg 15,Utrecht,leverancier
5,6,SpeedCycle BV,Spoorstraat 12,Eindhoven,fabrikant
6,7,UrbanBike Co.,Keizersgracht 45,Amsterdam,fabrikant
7,8,HollandRider,Marktstraat 9,Utrecht,fabrikant
8,9,EcoWheelers,Kade 33,Delft,fabrikant
9,10,DutchMotion,Westplein 7,Rotterdam,fabrikant
10,11,NordicBike,Prinsestraat 18,Groningen,fabrikant
11,12,CycleTech,Boslaan 60,Den Haag,fabrikant
12,13,GreenGear,Leliestraat 24,Nijmegen,fabrikant
13,14,FastFrame,Rivierlaan 3,Maastricht,fabrikant
14,15,OranjeFiets,Brink 88,Zwolle,fabrikant
15,16,GoeieSnelheid,Laan van Meerdervoort 20,Den Haag,fabrikant

# Dim_Product

In [581]:
dwh_product      = pd.read_sql_query('SELECT * FROM Dim_Product', DWH)
df_accessoire_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_accessoire', SDM)
df_accessoire_ai = pd.read_sql_query('SELECT * FROM accessoire_inkoop_accessoire', SDM)
df_fiets_o       = pd.read_sql_query('SELECT * FROM onderhoud_fiets', SDM)
df_fiets_fv      = pd.read_sql_query('SELECT * FROM fiets_verkoop_fiets', SDM)
df_fiets_fi      = pd.read_sql_query('SELECT * FROM fiets_inkoop_fiets', SDM)

df_accessoire_av = df_accessoire_av.drop('accessoirenr', axis=1)
df_accessoire_ai = df_accessoire_ai.drop('accessoirenr', axis=1)
df_fiets_o       = df_fiets_o.drop('fietsnr', axis=1)
df_fiets_fv      = df_fiets_fv.drop('fietsnr', axis=1)
df_fiets_fi      = df_fiets_fi.drop('fietsnr', axis=1)

df_accessoire_combined = pd.concat([df_accessoire_av, df_accessoire_ai]).drop_duplicates().reset_index(drop=True)
df_fiets_combined      = pd.concat([df_fiets_o, df_fiets_fv, df_fiets_fi]).drop_duplicates().reset_index(drop=True)

df_accessoire_combined.insert(0, 'categorie', 'accessoire')
df_accessoire_combined.rename(columns={'naam': 'type_product', 'productnaam': 'type_product', 'leverancier': 'partner'}, inplace=True)

df_fiets_combined.insert(0, 'categorie', 'fiets')
df_fiets_combined.rename(columns={'fabrikant': 'partner', 'type': 'type_product'}, inplace=True)

df_product_combined = pd.concat([df_accessoire_combined, df_fiets_combined]).drop_duplicates().reset_index(drop=True)

# ── Map partner name → partnernr ──────────────────────────────────────────────
# Build a lookup: naam -> partnernr from Dim_Partner
partner_lookup = df_partner_combined.set_index('naam')['partnernr']
df_product_combined['partner'] = df_product_combined['partner'].map(partner_lookup)

# ── Merge with existing Dim_Product and save ──────────────────────────────────
dwh_product = pd.concat([dwh_product, df_product_combined]).drop_duplicates().reset_index(drop=True)
dwh_product['productnr'] = range(1, len(dwh_product) + 1)
dwh_product['omzet'] = dwh_product['standaardprijs'] - dwh_product['inkoopprijs']

dwh_product.to_sql('Dim_Product', DWH, if_exists='replace', index=False)
dwh_product

,productnr,categorie,soort,merk,type_product,standaardprijs,inkoopprijs,omzet,kleur,partner
0,1,accessoire,Verlichting,NaN,LED voorlamp,14.99,8.5,6.49,NaN,NaN
1,2,accessoire,Verlichting,NaN,LED achterlicht,12.99,7.25,5.74,NaN,NaN
2,3,accessoire,Verlichting,NaN,USB-oplaadbare fietslamp,24.95,15.0,9.95,NaN,NaN
3,4,accessoire,Sloten,NaN,Ringslot AXA,19.95,11.4,8.55,NaN,NaN
4,5,accessoire,Sloten,NaN,Ketting met cijferslot,17.5,10.0,7.5,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
113,114,fiets,Elektrische fiets,FastFrame,ELE-120,731.83,576.62,155.21,Grijs,NaN
114,115,fiets,Racefiets,FastFrame,RAC-797,399.31,327.02,72.29,Rood,NaN
115,116,fiets,Stadsfiets,OranjeFiets,STA-974,731.99,622.99,109.0,Geel,NaN
116,117,fiets,Racefiets,OranjeFiets,RAC-701,589.5,513.51,75.99,Geel,NaN
117,118,fiets,Elektrische fiets,OranjeFiets,ELE-507,997.58,772.38,225.2,Wit,NaN

## Feit_Verkoop

In [582]:
dwh_verkoop = pd.read_sql_query('SELECT * FROM Feit_Verkoop', DWH)

df_verkoop_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_verkoop', SDM)
df_verkoop_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_verkoop', SDM)

df_verkoop_av = df_verkoop_av.drop('accessoire_verkoopnr', axis=1)
df_verkoop_fv = df_verkoop_fv.drop('fiets_verkoopnr', axis=1)

df_verkoop_av

         datum  aantal  verkoopprijs  klant  accessoire  monteur
0   2024-01-23       3         13.90      9           1        5
1   2024-10-03       2         11.27      7           1        7
2   2024-10-30       2         37.21      5           7        7
3   2024-11-16       1         10.71      9          10        2
4   2024-01-02       4         15.20     20           1        9
..         ...     ...           ...    ...         ...      ...
95  2024-01-10       3         15.56     12           5        5
96  2024-08-25       4         32.73      1           6        8
97  2024-09-29       2         12.62      3           1        4
98  2024-04-12       3         18.90      1           5        3
99  2024-10-27       4         12.67     18           5       10

[100 rows x 6 columns]

In [583]:
df_verkoop_fv

          datum  aantal  verkoopprijs  klant  fiets  monteur
0    2024-03-09       3       1020.48     25     61        6
1    2024-07-12       1       1391.84     23     58        5
2    2024-11-21       2       1891.33      2     45       10
3    2024-05-26       3        995.53      9     29        5
4    2024-04-15       2       1568.90     13     38       10
..          ...     ...           ...    ...    ...      ...
145  2024-07-02       1        902.77     14     10        4
146  2024-02-14       3       1159.80      6      1        8
147  2024-09-16       3       1075.78     19     68        7
148  2024-04-27       3       1581.13      9     38        3
149  2024-11-21       2        911.00      8     47        2

[150 rows x 6 columns]

In [584]:
dwh_verkoop

Empty DataFrame
Columns: [verkoopnr, datum, aantal, standaardprijs, verkoopprijs, korting, klant, accessoire, product, monteur]
Index: []