# Populating DWH

## Import libraries

In [59]:
import sqlite3
import pandas as pd
from datetime import datetime

## Define connections

In [60]:
SDM = sqlite3.connect('../SDM/BikeToDriveSDM.db')
DWH = sqlite3.connect('BikeToDriveDWH.db')

## Dim_Klant

In [61]:
df_klant_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_klant', SDM)
df_klant_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_klant', SDM)

df_klant_av = df_klant_av.drop('klantnr', axis=1)
df_klant_fv = df_klant_fv.drop('klantnr', axis=1)

df_klant_combined = pd.concat([df_klant_av, df_klant_fv]).drop_duplicates().reset_index(drop=True)

df_klant_combined.insert(0, 'klantnr', range(1, len(df_klant_combined) + 1))

df_klant_combined['geboortedatum'] = df_klant_combined['geboortedatum']

df_klant_combined.to_sql('Dim_Klant', DWH, if_exists='append', index=False)

df_klant_combined

,klantnr,naam,adres,woonplaats,geslacht,geboortedatum
0,1,Jan Jansen,Kerkstraat 12,Amsterdam,M,1985-03-22
1,2,Sophie de Boer,Lindelaan 8,Rotterdam,V,1990-07-11
2,3,Pieter Visser,Havenstraat 3,Den Haag,M,1978-11-05
3,4,Emma Smit,Boomgaard 22,Haarlem,V,1995-02-18
4,5,Tom Bakker,Stationsweg 44,Leiden,M,1982-09-09
5,6,Lisa Meijer,Dijkstraat 10,Zaandam,V,1993-12-30
6,7,Bart de Vries,Brouwersgracht 7,Delft,M,1976-06-06
7,8,Julia van Dijk,Plataanlaan 5,Hoorn,V,2000-01-15
8,9,Kevin Mol,Singel 99,Alkmaar,M,1989-08-01
9,10,Nina Groen,Waterstraat 16,Schiedam,V,1991-05-25
10,11,Daan Willems,Parklaan 31,Haarlem,M,1987-10-12
11,12,Eva Vos,Zomerweg 2,Zoetermeer,V,1996-04-03
12,13,Rik de Jong,Noorderstraat 88,Hilversum,M,1980-12-21
13,14,Mila Kuipers,Heemraadssingel 15,Rotterdam,V,1998-09-17
14,15,Sam Reinders,Beethovenlaan 13,Haarlem,M,1983-01-29
15,16,Fleur Schouten,Tulpenstraat 5,Amsterdam,V,1994-06-08
16,17,Lars van den Berg,Kade 101,Leiden,M,1988-03-02
17,18,Tess van Leeuwen,Markt 22,Dordrecht,V,1997-07-19
18,19,Jesse van Dam,Zuidlaan 7,Alphen aan den Rijn,M,1981-11-27
19,20,Noa Blom,Vondelstraat 18,Zaandam,V,2002-02-10
20,21,Robin Dekker,Rozenstraat 4,Delft,M,1992-11-23
21,22,Lieke de Wit,Tulpenpad 19,Den Haag,V,1986-07-12
22,23,Jeroen Hermans,Klaprooslaan 6,Zaandam,M,1999-05-04
23,24,Tessa van Vliet,Nieuwstraat 12,Leiden,V,2001-03-18
24,25,Bas Hendriks,IJsselstraat 2,Rotterdam,M,1984-10-30
25,26,Luna Hoekstra,Hortensialaan 1,Amstelveen,V,1997-08-07
26,27,Noah de Groot,Burgemeesterlaan 9,Haarlem,M,1990-12-02
27,28,Amber Peeters,Merellaan 18,Hoofddorp,V,1995-06-21
28,29,Mats Jonker,Kasteelstraat 7,Schiedam,M,1988-01-05
29,30,Isis Mulder,Goudenregenstraat 11,Dordrecht,V,2000-09-28

## Dim_Filiaal

In [62]:
df_filiaal_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_filiaal', SDM)
df_filiaal_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_filiaal', SDM)
df_filiaal_o = pd.read_sql_query('SELECT * FROM onderhoud_filiaal', SDM)

df_filiaal_av = df_filiaal_av.drop('filiaalnr', axis=1)
df_filiaal_fv = df_filiaal_fv.drop('filiaalnr', axis=1)
df_filiaal_o = df_filiaal_o.drop('filiaalnr', axis=1)

df_filiaal_combined = pd.concat([df_filiaal_av, df_filiaal_fv, df_filiaal_o]).drop_duplicates().reset_index(drop=True)

df_filiaal_combined.insert(0, 'filiaalnr', range(1, len(df_filiaal_combined) + 1))

df_filiaal_combined.to_sql('Dim_Filiaal', DWH, if_exists='append', index=False)

df_filiaal_combined

   filiaalnr                    naam              adres      provincie
0          1     BikeWorld Amsterdam  Prinsengracht 100  Noord-Holland
1          2     FietsGigant Haarlem     Grote Markt 22  Noord-Holland
2          3  FietsExpress Rotterdam      Coolsingel 55   Zuid-Holland
3          4        CycleCity Leiden      Breestraat 48   Zuid-Holland
4          5       ZaanFiets Zaandam        Damstraat 5  Noord-Holland

## Dim_Monteur

In [63]:
df_monteur_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_monteur', SDM)
df_monteur_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_monteur', SDM)
df_monteur_o = pd.read_sql_query('SELECT * FROM onderhoud_monteur', SDM)

df_monteur_av = df_monteur_av.drop('monteurnr', axis=1)
df_monteur_fv = df_monteur_fv.drop('monteurNr', axis=1)
df_monteur_o = df_monteur_o.drop('monteurNr', axis=1)

df_monteur_combined = pd.concat([df_monteur_av, df_monteur_fv, df_monteur_o]).drop_duplicates().reset_index(drop=True)

df_monteur_combined.insert(0, 'monteurnr', range(1, len(df_monteur_combined) + 1))

df_monteur_combined.to_sql('Dim_Monteur', DWH, if_exists='append', index=False)
df_monteur_combined

    monteurnr             naam  woonplaats  uurloon  filiaal
0           1     Tom van Dijk   Amsterdam    19.50        1
1           2   Lisa Verhoeven  Amstelveen    18.75        1
2           3    Kevin Jaspers     Zaandam    20.00        1
3           4     Romy Willems     Haarlem    17.80        2
4           5    Daan de Groot   Rotterdam    21.00        3
5           6  Sophie de Leeuw    Schiedam    19.90        3
6           7   Mark van Vliet   Dordrecht    20.25        3
7           8     Jesse Peters      Leiden    16.95        4
8           9       Eva Meijer  Zoetermeer    18.40        4
9          10   Milan de Bruin     Zaandam    17.25        2
10         11   Milan de Bruin     Zaandam    17.25        5
11         12   Sara de Koning     Haarlem    19.20        1
12         13       Nick Smits   Rotterdam    20.50        1
13         14     Laura Smeets   Amsterdam    18.80        1
14         15     Pim Scholten      Leiden    17.90        5
15         16    Tijn Hendriks     Zaandam    17.10        5

## Dim_Partner

In [64]:
df_leverancier_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_leverancier', SDM)
df_leverancier_ai = pd.read_sql_query('SELECT * FROM accessoire_inkoop_leverancier', SDM)

df_fabrikant_o = pd.read_sql_query('SELECT * FROM onderhoud_fabrikant', SDM)
df_fabrikant_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_fabrikant', SDM)
df_fabrikant_fi = pd.read_sql_query('SELECT * FROM fiets_inkoop_fabrikant', SDM)

df_leverancier_av = df_leverancier_av.drop('leveranciernr', axis=1)
df_leverancier_ai = df_leverancier_ai.drop('leveranciernr', axis=1)
df_fabrikant_o = df_fabrikant_o.drop('fabrikantnr', axis=1)
df_fabrikant_fv = df_fabrikant_fv.drop('fabrikantnr', axis=1)
df_fabrikant_fi = df_fabrikant_fi.drop('fabrikantnr', axis=1)

df_leverancier_combined = pd.concat([df_leverancier_av, df_leverancier_ai]).drop_duplicates().reset_index(drop=True)
df_fabrikant_combined   = pd.concat([df_fabrikant_o, df_fabrikant_fv, df_fabrikant_fi]).drop_duplicates().reset_index(drop=True)

df_leverancier_combined['type_partner'] = 'leverancier'
df_leverancier_combined.rename(columns={'woonplaats': 'plaats'}, inplace=True)
df_fabrikant_combined['type_partner'] = 'fabrikant'

df_partner_combined = pd.concat([df_leverancier_combined, df_fabrikant_combined]).drop_duplicates().reset_index(drop=True)
df_partner_combined.insert(0, 'partnernr', range(1, len(df_partner_combined) + 1))

df_partner_combined.to_sql('Dim_Partner', DWH, if_exists='append', index=False)
df_partner_combined

,partnernr,naam,adres,plaats,type_partner
0,1,BikeParts BV,Fietsenstraat 12,Amsterdam,leverancier
1,2,CycleSupplies,Rembrandtlaan 7,Rotterdam,leverancier
2,3,TwoWheels Trading,Marktplein 5,Den Haag,leverancier
3,4,DutchBike Import,Kade 22,Leiden,leverancier
4,5,UrbanGear NL,Stationsweg 15,Utrecht,leverancier
5,6,SpeedCycle BV,Spoorstraat 12,Eindhoven,fabrikant
6,7,UrbanBike Co.,Keizersgracht 45,Amsterdam,fabrikant
7,8,HollandRider,Marktstraat 9,Utrecht,fabrikant
8,9,EcoWheelers,Kade 33,Delft,fabrikant
9,10,DutchMotion,Westplein 7,Rotterdam,fabrikant
10,11,NordicBike,Prinsestraat 18,Groningen,fabrikant
11,12,CycleTech,Boslaan 60,Den Haag,fabrikant
12,13,GreenGear,Leliestraat 24,Nijmegen,fabrikant
13,14,FastFrame,Rivierlaan 3,Maastricht,fabrikant
14,15,OranjeFiets,Brink 88,Zwolle,fabrikant
15,16,GoeieSnelheid,Laan van Meerdervoort 20,Den Haag,fabrikant

# Dim_Product

In [65]:
df_accessoire_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_accessoire', SDM)
df_accessoire_ai = pd.read_sql_query('SELECT * FROM accessoire_inkoop_accessoire', SDM)
df_fiets_o = pd.read_sql_query('SELECT * FROM onderhoud_fiets', SDM)
df_fiets_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_fiets', SDM)
df_fiets_fi = pd.read_sql_query('SELECT * FROM fiets_inkoop_fiets', SDM)

df_leverancier_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_leverancier', SDM)
df_leverancier_ai = pd.read_sql_query('SELECT * FROM accessoire_inkoop_leverancier', SDM)
df_fabrikant_o = pd.read_sql_query('SELECT * FROM onderhoud_fabrikant', SDM)
df_fabrikant_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_fabrikant', SDM)
df_fabrikant_fi = pd.read_sql_query('SELECT * FROM fiets_inkoop_fabrikant', SDM)

df_accessoire_av = pd.merge(df_accessoire_av, df_leverancier_av, left_on='leverancier', right_on='leveranciernr', how='left', suffixes=('_accessoire', '_leverancier'))
df_accessoire_av.rename(columns={'naam_accessoire': 'type_product'}, inplace=True)
df_accessoire_av.drop(columns=['leveranciernr', 'leverancier', 'adres', 'woonplaats'], inplace=True, errors='ignore')
df_accessoire_av = pd.merge(df_accessoire_av, df_partner_combined, left_on='naam_leverancier', right_on='naam', how='left')
df_accessoire_av.drop(columns=['naam_leverancier', 'naam', 'adres', 'plaats', 'type_partner'], inplace=True, errors='ignore')

df_accessoire_ai = pd.merge(df_accessoire_ai, df_leverancier_ai, left_on='leverancier', right_on='leveranciernr', how='left', suffixes=('_accessoire', '_leverancier'))
df_accessoire_ai.rename(columns={'naam_accessoire': 'type_product'}, inplace=True)
df_accessoire_ai.drop(columns=['leveranciernr', 'leverancier', 'adres', 'woonplaats'], inplace=True, errors='ignore')
df_accessoire_ai = pd.merge(df_accessoire_ai, df_partner_combined, left_on='naam_leverancier', right_on='naam', how='left')
df_accessoire_ai.drop(columns=['naam_leverancier', 'naam', 'adres', 'plaats', 'type_partner'], inplace=True, errors='ignore')   

df_fiets_o = pd.merge(df_fiets_o, df_fabrikant_o, left_on='fabrikant', right_on='fabrikantnr', how='left')
df_fiets_o.drop(columns=['fabrikantnr', 'fabrikant', 'adres', 'woonplaats', 'plaats'], inplace=True, errors='ignore')
df_fiets_o = pd.merge(df_fiets_o, df_partner_combined, left_on='naam', right_on='naam', how='left')
df_fiets_o.drop(columns=['naam_fabrikant', 'naam', 'adres', 'plaats', 'type_partner'], inplace=True, errors='ignore')
df_fiets_o.rename(columns={'type': 'type_product'}, inplace=True)

df_fiets_fv = pd.merge(df_fiets_fv, df_fabrikant_fv, left_on='fabrikant', right_on='fabrikantnr', how='left')
df_fiets_fv.drop(columns=['fabrikantnr', 'fabrikant', 'adres', 'woonplaats', 'plaats'], inplace=True, errors='ignore')
df_fiets_fv = pd.merge(df_fiets_fv, df_partner_combined, left_on='naam', right_on='naam', how='left')
df_fiets_fv.drop(columns=['naam_fabrikant', 'naam', 'adres', 'plaats', 'type_partner'], inplace=True, errors='ignore')
df_fiets_fv.rename(columns={'type': 'type_product'}, inplace=True)

df_fiets_fi = pd.merge(df_fiets_fi, df_fabrikant_fi, left_on='fabrikant', right_on='fabrikantnr', how='left')
df_fiets_fi.drop(columns=['fabrikantnr', 'fabrikant', 'adres', 'woonplaats', 'plaats'], inplace=True, errors='ignore')  
df_fiets_fi = pd.merge(df_fiets_fi, df_partner_combined, left_on='naam', right_on='naam', how='left')
df_fiets_fi.drop(columns=['naam_fabrikant', 'naam', 'adres', 'plaats', 'type_partner'], inplace=True, errors='ignore')
df_fiets_fi.rename(columns={'type': 'type_product'}, inplace=True)

df_accessoire_av = df_accessoire_av.drop('accessoirenr', axis=1)
df_accessoire_ai = df_accessoire_ai.drop('accessoirenr', axis=1)
df_fiets_o = df_fiets_o.drop('fietsnr', axis=1)
df_fiets_fv = df_fiets_fv.drop('fietsnr', axis=1)
df_fiets_fi = df_fiets_fi.drop('fietsnr', axis=1)

df_accessoire_combined = pd.concat([df_accessoire_av, df_accessoire_ai]).drop_duplicates().reset_index(drop=True)
df_accessoire_combined['categorie'] = 'accessoire'
df_fiets_combined = pd.concat([df_fiets_o, df_fiets_fv, df_fiets_fi]).drop_duplicates().reset_index(drop=True)
df_fiets_combined['categorie'] = 'fiets'
df_product_combined = pd.concat([df_accessoire_combined, df_fiets_combined]).drop_duplicates().reset_index(drop=True)

df_product_combined['omzet'] = df_product_combined['standaardprijs'] - df_product_combined['inkoopprijs']
df_product_combined.insert(0, 'productnr', range(1, len(df_product_combined) + 1))

df_product_combined.to_sql('Dim_Product', DWH, if_exists='append', index=False)

df_product_combined

,productnr,type_product,standaardprijs,inkoopprijs,soort,partnernr,categorie,merk,kleur,omzet
0,1,LED voorlamp,14.99,8.50,Verlichting,1,accessoire,NaN,NaN,6.49
1,2,LED achterlicht,12.99,7.25,Verlichting,1,accessoire,NaN,NaN,5.74
2,3,USB-oplaadbare fietslamp,24.95,15.00,Verlichting,1,accessoire,NaN,NaN,9.95
3,4,Ringslot AXA,19.95,11.40,Sloten,1,accessoire,NaN,NaN,8.55
4,5,Ketting met cijferslot,17.50,10.00,Sloten,2,accessoire,NaN,NaN,7.50
...,...,...,...,...,...,...,...,...,...,...
113,114,ELE-120,731.83,576.62,Elektrische fiets,14,fiets,FastFrame,Grijs,155.21
114,115,RAC-797,399.31,327.02,Racefiets,14,fiets,FastFrame,Rood,72.29
115,116,STA-974,731.99,622.99,Stadsfiets,15,fiets,OranjeFiets,Geel,109.00
116,117,RAC-701,589.50,513.51,Racefiets,15,fiets,OranjeFiets,Geel,75.99
117,118,ELE-507,997.58,772.38,Elektrische fiets,15,fiets,OranjeFiets,Wit,225.20

## Dim_Datum & Dim_Maand

In [66]:
dates_verkoop_av = pd.read_sql_query('SELECT datum FROM accessoire_verkoop_verkoop', SDM)['datum']
dates_verkoop_fv = pd.read_sql_query('SELECT datum FROM fiets_verkoop_verkoop', SDM)['datum']
dates_onderhoud  = pd.read_sql_query('SELECT datum FROM onderhoud_onderhoud', SDM)['datum']

all_dates = pd.concat([dates_verkoop_av, dates_verkoop_fv, dates_onderhoud]).drop_duplicates()
all_dates = pd.to_datetime(all_dates, errors='coerce').dropna().drop_duplicates().sort_values().reset_index(drop=True)

maand_namen  = {1:'Januari', 2:'Februari', 3:'Maart', 4:'April', 5:'Mei', 6:'Juni',
				7:'Juli', 8:'Augustus', 9:'September', 10:'Oktober', 11:'November', 12:'December'}
kwartaal_map = {1:'Q1', 2:'Q1', 3:'Q1', 4:'Q2', 5:'Q2', 6:'Q2',
				7:'Q3', 8:'Q3', 9:'Q3', 10:'Q4', 11:'Q4', 12:'Q4'}

df_maand = pd.DataFrame({
	'maandnr': all_dates.dt.month,
	'jaar':    all_dates.dt.year
}).drop_duplicates().sort_values(['jaar', 'maandnr']).reset_index(drop=True)

df_maand.insert(0, 'maand_id', range(1, len(df_maand) + 1))
df_maand['maand']    = df_maand['maandnr'].map(maand_namen)
df_maand['kwartaal'] = df_maand['maandnr'].map(kwartaal_map)

df_maand.to_sql('Dim_Maand', DWH, if_exists='append', index=False)

maand_lookup = df_maand.set_index(['maandnr', 'jaar'])['maand_id']

df_maand

    maand_id  maandnr  jaar      maand kwartaal
0          1        1  2024    Januari       Q1
1          2        2  2024   Februari       Q1
2          3        3  2024      Maart       Q1
3          4        4  2024      April       Q2
4          5        5  2024        Mei       Q2
5          6        6  2024       Juni       Q2
6          7        7  2024       Juli       Q3
7          8        8  2024   Augustus       Q3
8          9        9  2024  September       Q3
9         10       10  2024    Oktober       Q4
10        11       11  2024   November       Q4
11        12       12  2024   December       Q4

In [67]:
df_datum = pd.DataFrame({'datum': all_dates})
df_datum['dag'] = df_datum['datum'].dt.day
df_datum['maandnr'] = df_datum['datum'].dt.month
df_datum['jaar'] = df_datum['datum'].dt.year
df_datum['maand_id'] = df_datum.apply(lambda r: maand_lookup.get((r['maandnr'], r['jaar'])), axis=1)
df_datum['datum'] = df_datum['datum'].dt.strftime('%Y-%m-%d')
df_datum = df_datum[['datum', 'dag', 'maand_id']]

df_datum.to_sql('Dim_Datum', DWH, if_exists='append', index=False)

df_datum

          datum  dag  maand_id
0    2024-01-02    2         1
1    2024-01-06    6         1
2    2024-01-08    8         1
3    2024-01-10   10         1
4    2024-01-11   11         1
..          ...  ...       ...
191  2024-12-26   26        12
192  2024-12-27   27        12
193  2024-12-28   28        12
194  2024-12-30   30        12
195  2024-12-31   31        12

[196 rows x 3 columns]

## Feit_Verkoop

In [68]:
df_verkoop_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_verkoop', SDM)
df_verkoop_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_verkoop', SDM)

df_accessoire_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_accessoire', SDM)
df_monteur_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_monteur', SDM)
df_klant_av = pd.read_sql_query('SELECT * FROM accessoire_verkoop_klant', SDM)
df_fiets_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_fiets', SDM)
df_monteur_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_monteur', SDM)
df_klant_fv = pd.read_sql_query('SELECT * FROM fiets_verkoop_klant', SDM)

df_verkoop_av = pd.merge(df_verkoop_av, df_accessoire_av, left_on='accessoire', right_on='accessoirenr', how='left')
df_verkoop_av = df_verkoop_av.drop(columns=['inkoopprijs', 'soort', 'leverancier', 'accessoirenr', 'accessoire'], errors='ignore')
df_verkoop_av = pd.merge(df_verkoop_av, df_product_combined, left_on='naam', right_on='type_product', how='left')
df_verkoop_av = df_verkoop_av.drop(columns=['inkoopprijs', 'naam', 'soort', 'partnernr', 'merk', 'kleur', 'standaardprijs_y', 'type'], errors='ignore')
df_verkoop_av.rename(columns={'standaardprijs_x': 'standaardprijs', 'productnr': 'product'}, inplace=True)
df_verkoop_av.rename(columns={'product': 'productnr'}, inplace=True)

df_verkoop_av = pd.merge(df_verkoop_av, df_klant_fv, left_on='klant', right_on='klantnr', how='left')
df_verkoop_av = df_verkoop_av.drop(columns=['klantnr', 'geslacht', 'adres', 'woonplaats', 'geboortedatum'], errors='ignore')
df_verkoop_av = pd.merge(df_verkoop_av, df_klant_combined, left_on='naam', right_on='naam', how='left')
df_verkoop_av = df_verkoop_av.drop(columns=['naam', 'adres', 'woonplaats', 'geboortedatum', 'geslacht', 'klant'], errors='ignore')
df_verkoop_av.rename(columns={'product': 'productnr'}, inplace=True)

df_verkoop_av = pd.merge(df_verkoop_av, df_monteur_av, left_on='monteur', right_on='monteurnr', how='left')
df_verkoop_av = df_verkoop_av.drop(columns=['woonplaats', 'uurloon', 'filiaal', 'monteurnr'], errors='ignore')
df_verkoop_av = pd.merge(df_verkoop_av, df_monteur_combined, left_on='naam', right_on='naam', how='left')
df_verkoop_av = df_verkoop_av.drop(columns=['naam', 'woonplaats', 'uurloon', 'filiaal', 'monteur'], errors='ignore')
df_verkoop_av.rename(columns={'product': 'productnr'}, inplace=True)

df_verkoop_fv = pd.merge(df_verkoop_fv, df_fiets_fv, left_on='fiets', right_on='fietsnr', how='left')
df_verkoop_fv = df_verkoop_fv.drop(columns=['fietsnr', 'soort', 'merk', 'standaardprijs', 'kleur', 'fabrikant', 'inkoopprijs'], errors='ignore')
df_verkoop_fv = pd.merge(df_verkoop_fv, df_product_combined, left_on='type', right_on='type_product', how='left')
df_verkoop_fv = df_verkoop_fv.drop(columns=['type', 'inkoopprijs', 'soort', 'merk', 'kleur', 'partnernr', 'fiets'], errors='ignore')

df_verkoop_fv = pd.merge(df_verkoop_fv, df_klant_fv, left_on='klant', right_on='klantnr', how='left')
df_verkoop_fv = df_verkoop_fv.drop(columns=['klantnr', 'geslacht', 'adres', 'woonplaats', 'geboortedatum'], errors='ignore')
df_verkoop_fv = pd.merge(df_verkoop_fv, df_klant_combined, left_on='naam', right_on='naam', how='left')
df_verkoop_fv = df_verkoop_fv.drop(columns=['naam', 'adres', 'woonplaats', 'geboortedatum', 'geslacht', 'klant'], errors='ignore')

df_verkoop_fv = pd.merge(df_verkoop_fv, df_monteur_fv, left_on='monteur', right_on='monteurNr', how='left')
df_verkoop_fv = df_verkoop_fv.drop(columns=['woonplaats', 'uurloon', 'filiaal', 'monteurNr'], errors='ignore')
df_verkoop_fv = pd.merge(df_verkoop_fv, df_monteur_combined, left_on='naam', right_on='naam', how='left')
df_verkoop_fv = df_verkoop_fv.drop(columns=['naam', 'woonplaats', 'uurloon', 'filiaal', 'monteur'], errors='ignore')

df_verkoop_av = df_verkoop_av.drop('accessoire_verkoopnr', axis=1)
df_verkoop_fv = df_verkoop_fv.drop('fiets_verkoopnr', axis=1)

df_verkoop_combined = pd.concat([df_verkoop_av, df_verkoop_fv]).drop_duplicates().reset_index(drop=True)
df_verkoop_combined.insert(0, 'verkoopnr', range(1, len(df_verkoop_combined) + 1))
df_verkoop_combined['korting'] = df_verkoop_combined['standaardprijs'] - df_verkoop_combined['verkoopprijs']
df_verkoop_combined['totaalprijs'] = df_verkoop_combined['verkoopprijs'] * df_verkoop_combined['aantal']
df_verkoop_combined = df_verkoop_combined.drop('type_product', axis=1)
df_verkoop_combined = df_verkoop_combined.drop('categorie', axis=1)
df_verkoop_combined = df_verkoop_combined.drop('omzet', axis=1)


df_verkoop_combined.to_sql('Feit_Verkoop', DWH, if_exists='append', index=False)

df_verkoop_combined

,verkoopnr,datum,aantal,verkoopprijs,standaardprijs,productnr,klantnr,monteurnr,korting,totaalprijs
0,1,2024-01-23,3,13.90,14.99,1,9,5,1.09,41.70
1,2,2024-10-03,2,11.27,14.99,1,7,7,3.72,22.54
2,3,2024-10-30,2,37.21,39.95,7,5,7,2.74,74.42
3,4,2024-11-16,1,10.71,11.99,10,9,2,1.28,10.71
4,5,2024-01-02,4,15.20,14.99,1,25,9,-0.21,60.80
...,...,...,...,...,...,...,...,...,...,...
285,286,2024-02-14,3,1159.80,962.33,44,6,8,-197.47,3479.40
286,287,2024-09-16,3,1075.78,980.16,111,24,7,-95.62,3227.34
287,288,2024-04-27,3,1581.13,341.93,81,9,3,-1239.20,4743.39
288,289,2024-11-21,2,911.00,547.79,46,8,2,-363.21,1822.00
289,290,2024-11-21,2,911.00,837.18,90,8,2,-73.82,1822.00

## Feit_Inkoop

In [69]:
df_inkoop_ai = pd.read_sql_query('SELECT * FROM accessoire_inkoop_inkoop', SDM)
df_inkoop_fi = pd.read_sql_query('SELECT * FROM fiets_inkoop_inkoop', SDM)

df_accessoire_ai = pd.read_sql_query('SELECT * FROM accessoire_inkoop_accessoire', SDM)
df_fiets_fi = pd.read_sql_query('SELECT * FROM fiets_inkoop_fiets', SDM)

df_inkoop_ai = pd.merge(df_inkoop_ai, df_accessoire_ai, left_on='accessoire', right_on='accessoirenr', how='left')
df_inkoop_ai = df_inkoop_ai.drop(columns=['accessoirenr', 'standaardprijs', 'soort', 'accessoire', 'inkoopprijs', 'leverancier'], errors='ignore')
df_inkoop_ai = pd.merge(df_inkoop_ai, df_product_combined, left_on='naam', right_on='type_product', how='left')
df_inkoop_ai = df_inkoop_ai.drop(columns=['type', 'soort', 'standaardprijs', 'soort', 'merk', 'kleur', 'naam', 'type_product'], errors='ignore')

df_inkoop_fi = pd.merge(df_inkoop_fi, df_fiets_fi, left_on='fiets', right_on='fietsnr', how='left')
df_inkoop_fi = df_inkoop_fi.drop(columns=['merk', 'fietsnr', 'soort', 'standaardprijs', 'inkoopprijs', 'kleur', 'fabrikant', 'fiets'], errors='ignore')
df_inkoop_fi = pd.merge(df_inkoop_fi, df_product_combined, left_on='type', right_on='type_product', how='left')
df_inkoop_fi = df_inkoop_fi.drop(columns=['type', 'standaardprijs', 'soort', 'merk', 'kleur', 'type_product'], errors='ignore')

df_inkoop_ai = df_inkoop_ai.drop('inkoopnr', axis=1)
df_inkoop_fi = df_inkoop_fi.drop('inkoopnr', axis=1)

df_inkoop_combined = pd.concat([df_inkoop_ai, df_inkoop_fi]).drop_duplicates().reset_index(drop=True)
df_inkoop_combined.insert(0, 'inkoopnr', range(1, len(df_inkoop_combined) + 1))
df_inkoop_combined['totaalprijs'] = df_inkoop_combined['inkoopprijs'] * df_inkoop_combined['aantal']
df_inkoop_combined = df_inkoop_combined.drop('categorie', axis=1)
df_inkoop_combined = df_inkoop_combined.drop('omzet', axis=1)

df_inkoop_combined.to_sql('Feit_Inkoop', DWH, if_exists='append', index=False)
df_inkoop_combined

,inkoopnr,inkoopmaand,inkoopjaar,aantal,productnr,inkoopprijs,partnernr,totaalprijs
0,1,4,2024,38,7,24.90,2,946.20
1,2,8,2024,31,6,18.75,2,581.25
2,3,1,2024,41,2,7.25,1,297.25
3,4,1,2024,21,1,8.50,1,178.50
4,5,10,2024,31,4,11.40,1,353.40
...,...,...,...,...,...,...,...,...
153,154,4,2024,7,99,465.36,11,3257.52
154,155,12,2024,5,86,780.62,9,3903.10
155,156,11,2024,2,61,714.39,7,1428.78
156,157,7,2024,1,61,714.39,7,714.39
157,158,12,2024,5,69,725.11,7,3625.55

## Feit_Onderhoud

In [70]:
df_onderhoud_o = pd.read_sql_query('SELECT * FROM onderhoud_onderhoud', SDM)

df_fiets_o = pd.read_sql_query('SELECT * FROM onderhoud_fiets', SDM)
df_monteur_o = pd.read_sql_query('SELECT * FROM onderhoud_monteur', SDM)

df_onderhoud_o = pd.merge(df_onderhoud_o, df_fiets_o, left_on='fiets', right_on='fietsnr', how='left')
df_onderhoud_o = df_onderhoud_o.drop(columns=['fietsnr', 'soort', 'merk', 'standaardprijs', 'inkoopprijs', 'kleur', 'fabrikant'], errors='ignore')
df_onderhoud_o = pd.merge(df_onderhoud_o, df_product_combined, left_on='type', right_on='type_product', how='left')
df_onderhoud_o = df_onderhoud_o.drop(columns=['standaardprijs', 'soort', 'merk', 'kleur', 'partnernr', 'inkoopprijs', 'fiets'], errors='ignore')

df_onderhoud_o = pd.merge(df_onderhoud_o, df_monteur_o, left_on='monteur', right_on='monteurNr', how='left')
df_onderhoud_o = df_onderhoud_o.drop(columns=['monteurNr', 'woonplaats', 'uurloon', 'filiaal'], errors='ignore')
df_onderhoud_o = pd.merge(df_onderhoud_o, df_monteur_combined, left_on='naam', right_on='naam', how='left')
df_onderhoud_o = df_onderhoud_o.drop(columns=['naam', 'woonplaats', 'uurloon', 'filiaal', 'monteur'], errors='ignore')

df_onderhoud_o['duur'] = (
    pd.to_datetime(df_onderhoud_o['eindtijd'].str[:-1], format='%H:%M:%S.%f') -
    pd.to_datetime(df_onderhoud_o['starttijd'].str[:-1], format='%H:%M:%S.%f')
)

df_onderhoud_o['duur'] = df_onderhoud_o['duur'].apply(
    lambda x: f"{int(x.total_seconds()//3600):02}:{int((x.total_seconds()%3600)//60):02}"
)

df_onderhoud_o = df_onderhoud_o.drop('onderhoudnr', axis=1)
df_onderhoud_o.insert(0, 'onderhoudnr', range(1, len(df_onderhoud_o) + 1))
df_onderhoud_o = df_onderhoud_o.drop('type', axis=1)
df_onderhoud_o = df_onderhoud_o.drop('type_product', axis=1)
df_onderhoud_o = df_onderhoud_o.drop('categorie', axis=1)
df_onderhoud_o = df_onderhoud_o.drop('omzet', axis=1)

df_onderhoud_o.to_sql('Feit_Onderhoud', DWH, if_exists='append', index=False)

df_onderhoud_o

,onderhoudnr,datum,starttijd,eindtijd,productnr,monteurnr,duur
0,1,2024-12-28,15:00:00.0000000,16:00:00.0000000,23,15,01:00
1,2,2024-02-05,14:00:00.0000000,15:00:00.0000000,19,8,01:00
2,3,2024-08-01,10:00:00.0000000,11:00:00.0000000,15,15,01:00
3,4,2024-11-16,10:00:00.0000000,11:00:00.0000000,17,2,01:00
4,5,2024-08-01,11:00:00.0000000,12:00:00.0000000,36,16,01:00
5,6,2024-12-08,13:00:00.0000000,14:00:00.0000000,19,14,01:00
6,7,2024-05-14,11:00:00.0000000,12:00:00.0000000,16,8,01:00
7,8,2024-10-10,09:00:00.0000000,10:00:00.0000000,41,3,01:00
8,9,2024-06-29,08:00:00.0000000,09:00:00.0000000,19,13,01:00
9,10,2024-08-21,08:00:00.0000000,09:00:00.0000000,28,2,01:00
10,11,2024-08-20,08:00:00.0000000,09:00:00.0000000,40,8,01:00
11,12,2024-09-15,11:00:00.0000000,12:00:00.0000000,35,6,01:00
12,13,2024-05-27,08:00:00.0000000,09:00:00.0000000,26,9,01:00
13,14,2024-07-21,10:00:00.0000000,11:00:00.0000000,42,5,01:00
14,15,2024-02-03,12:00:00.0000000,13:00:00.0000000,21,16,01:00
15,16,2024-09-27,15:00:00.0000000,16:00:00.0000000,33,5,01:00
16,17,2024-12-21,12:00:00.0000000,13:00:00.0000000,38,9,01:00
17,18,2024-01-08,10:00:00.0000000,11:00:00.0000000,23,1,01:00
18,19,2024-11-12,12:00:00.0000000,13:00:00.0000000,25,9,01:00
19,20,2024-12-27,08:00:00.0000000,09:00:00.0000000,35,10,01:00
20,21,2024-12-27,08:00:00.0000000,09:00:00.0000000,35,11,01:00
21,22,2024-09-30,12:00:00.0000000,13:00:00.0000000,22,4,01:00
22,23,2024-05-07,11:00:00.0000000,12:00:00.0000000,25,7,01:00
23,24,2024-08-13,08:00:00.0000000,09:00:00.0000000,24,14,01:00
24,25,2024-07-27,11:00:00.0000000,12:00:00.0000000,35,8,01:00
25,26,2024-08-29,14:00:00.0000000,15:00:00.0000000,24,7,01:00
26,27,2024-12-14,08:00:00.0000000,09:00:00.0000000,38,8,01:00
27,28,2024-02-06,09:00:00.0000000,10:00:00.0000000,15,5,01:00
28,29,2024-11-15,11:00:00.0000000,12:00:00.0000000,25,10,01:00
29,30,2024-11-15,11:00:00.0000000,12:00:00.0000000,25,11,01:00
30,31,2024-05-19,11:00:00.0000000,12:00:00.0000000,32,13,01:00
31,32,2024-07-26,11:00:00.0000000,12:00:00.0000000,17,5,01:00
32,33,2024-02-23,13:00:00.0000000,14:00:00.0000000,23,13,01:00
33,34,2024-10-17,10:00:00.0000000,11:00:00.0000000,24,10,01:00
34,35,2024-10-17,10:00:00.0000000,11:00:00.0000000,24,11,01:00
35,36,2024-11-01,15:00:00.0000000,16:00:00.0000000,32,8,01:00
36,37,2024-10-04,15:00:00.0000000,16:00:00.0000000,21,5,01:00
37,38,2024-07-05,11:00:00.0000000,12:00:00.0000000,17,15,01:00
38,39,2024-01-28,09:00:00.0000000,10:00:00.0000000,19,13,01:00
39,40,2024-09-01,11:00:00.0000000,12:00:00.0000000,24,15,01:00
40,41,2024-09-23,09:00:00.0000000,10:00:00.0000000,27,5,01:00
41,42,2024-11-08,13:00:00.0000000,14:00:00.0000000,28,13,01:00
42,43,2024-12-31,14:00:00.0000000,15:00:00.0000000,42,3,01:00
43,44,2024-12-13,15:00:00.0000000,16:00:00.0000000,31,16,01:00
44,45,2024-02-23,15:00:00.0000000,16:00:00.0000000,20,2,01:00
45,46,2024-12-13,15:00:00.0000000,16:00:00.0000000,37,10,01:00
46,47,2024-12-13,15:00:00.0000000,16:00:00.0000000,37,11,01:00
47,48,2024-05-03,13:00:00.0000000,14:00:00.0000000,25,8,01:00
48,49,2024-08-10,08:00:00.0000000,09:00:00.0000000,41,4,01:00
49,50,2024-08-28,13:00:00.0000000,14:00:00.0000000,43,13,01:00
50,51,2024-12-11,14:00:00.0000000,15:00:00.0000000,16,6,01:00
51,52,2024-03-04,09:00:00.0000000,10:00:00.0000000,35,12,01:00
52,53,2024-07-03,12:00:00.0000000,13:00:00.0000000,22,6,01:00
53,54,2024-07-08,12:00:00.0000000,13:00:00.0000000,41,16,01:00

## Close connections

In [71]:
SDM.close()
DWH.close()